import Head from "next/head";
import Image from "next/image";

// Image
import tumbnail from "../public/hans-eiskonen-8Pm_A-OHJGg-unsplash.png";
import playback from "../public/play-back.png";
import play from "../public/play.png";
import playforward from "../public/play-forward.png";
import barra from "../public/barra.png";

// Styles
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Desafios Rocketseat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.card1}>
            <Image src={tumbnail} alt="" className={styles.tumbnail1} />
            <h2>Acorda Devinho</h2>
            <h3>Banda Rocketseat</h3>
            <div className={styles.player1}>
              <Image src={playback} alt="" className={styles.playback} />
              <Image src={play} alt="" className={styles.play} />
              <Image src={playforward} alt="" className={styles.playforward} />
            </div>
            <div className={styles.player2}>
              <Image src={barra} alt="" className={barra} />
              <div className={styles.timer}>
                <p className={styles.complete}>3:20</p>
                <p className={styles.incomplete}>00:12</p>
              </div>
            </div>
          </div>
          <div className={styles.card2}>
            <div className={styles.info1}>
              <Image src={tumbnail} alt="" width={84.03} height={84.03} className={styles.tumbnail2} />
              <div className={styles.info2}>
                <h2>Acorda Devinho</h2>
                <h3>Banda Rocketseat</h3>
              </div>
            </div>
            <div className={styles.player1}>
              <Image src={playback} alt="" className={styles.playback} />
              <Image src={play} alt="" className={styles.play} />
              <Image src={playforward} alt="" className={styles.playforward} />
            </div>
            <div className={styles.player2}>
              <Image src={barra} alt="" width={300.09} height={6} className={barra} />
              <div className={styles.timer}>
                <p className={styles.complete}>3:20</p>
                <p className={styles.incomplete2}>00:12</p>
              </div>
            </div>
          </div>
          <div className={styles.card3}>
            <div className={styles.info1}>
              <Image src={tumbnail} alt="" width={84.03} height={84.03} className={styles.tumbnail2} />
              <div className={styles.info2}>
                <h2>Acorda Devinho</h2>
                <h3>Banda Rocketseat</h3>
              </div>
            </div>
            <div className={styles.player1}>
              <Image src={playback} alt="" className={styles.playback} />
              <Image src={play} alt="" className={styles.play} />
              <Image src={playforward} alt="" className={styles.playforward} />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
